server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    #This is CRITICAL for React Router
    # Without this, refreshing any page gives 404!
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache static assets (JS, CSS, images)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}